
(function(){
function pad(n){return String(n).padStart(2,'0')}
function localISO(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function todayLocal(){return localISO(new Date())}
function tomorrowISO(){const d=new Date();d.setDate(d.getDate()+1);return localISO(d)}
function formatUA(iso){const p=String(iso||'').split('-');return p.length===3?`${p[2]}-${p[1]}-${p[0]}`:iso}
window.formatDateUA=window.formatDateUA||formatUA;
function serviceBySelect(){const title=document.getElementById('bookingService')?.value||'';return typeof services==='function'?services().find(s=>s.title===title):null}
function isUrgent(service){if(!service)return false;if(typeof serviceIsUrgent==='function')return serviceIsUrgent(service);return String(service.category||service.title||'').toLowerCase().includes('термін')}
function available(date){const service=serviceBySelect();const min=isUrgent(service)?todayLocal():tomorrowISO();if(date<min)return[];const keys=typeof takenKeys==='function'?takenKeys():[];return(typeof slots==='function'?slots():[]).filter(s=>s.date===date&&!keys.includes(`${s.date}_${s.time}`)&&!(typeof daysOff==='function'?daysOff():[]).includes(s.date))}
window.availableForBooking=available;
window.updateTimes=function(){const d=document.getElementById('bookingDate'),t=document.getElementById('bookingTime');if(!d||!t)return;const service=serviceBySelect();d.min=isUrgent(service)?todayLocal():tomorrowISO();const arr=d.value?available(d.value):[];t.innerHTML=!d.value?'<option value="">Спочатку оберіть дату</option>':arr.length?'<option value="">Оберіть час</option>'+arr.map(s=>`<option value="${s.time}">${s.time} — ${s.format==='offline'?'офлайн':'онлайн'}${s.city?', '+s.city:''}</option>`).join(''):'<option value="">Немає доступного часу</option>'}
window.renderBookingDateStrip=function(){const strip=document.getElementById('bookingDateStrip'),grid=document.getElementById('bookingTimeGrid'),dateInput=document.getElementById('bookingDate');if(!strip||!grid||!dateInput)return;const service=serviceBySelect(),urgent=isUrgent(service),start=new Date();if(!urgent)start.setDate(start.getDate()+1);const days=[];for(let i=0;i<21;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=localISO(d),arr=available(iso);if(arr.length)days.push({iso,label:formatUA(iso),weekday:d.toLocaleDateString('uk-UA',{weekday:'short'}),count:arr.length,urgentToday:urgent&&iso===todayLocal()})}strip.innerHTML=days.length?days.map(d=>`<button type="button" class="booking-date-card ${dateInput.value===d.iso?'active':''} ${d.urgentToday?'urgent-today':''}" data-date="${d.iso}"><strong>${d.label}</strong><br><small>${d.weekday} · ${d.count} год.</small></button>`).join(''):'<div class="booking-date-card normal-disabled">Немає доступних днів</div>';strip.querySelectorAll('[data-date]').forEach(btn=>btn.onclick=()=>{dateInput.value=btn.dataset.date;window.updateTimes();window.renderBookingDateStrip();window.renderBookingTimeGrid()});window.renderBookingTimeGrid()}
window.renderBookingTimeGrid=function(){const grid=document.getElementById('bookingTimeGrid'),dateInput=document.getElementById('bookingDate'),timeSelect=document.getElementById('bookingTime');if(!grid||!dateInput||!timeSelect)return;const arr=dateInput.value?available(dateInput.value):[];grid.innerHTML=arr.length?arr.map(s=>`<button type="button" class="time-pill ${timeSelect.value===s.time?'active':''}" data-time="${s.time}">${s.time}</button>`).join(''):'<div class="time-pill normal-disabled">Оберіть доступний день</div>';grid.querySelectorAll('[data-time]').forEach(btn=>btn.onclick=()=>{timeSelect.value=btn.dataset.time;window.renderBookingTimeGrid()})}
function toggleUrgentPanel(){const panel=document.getElementById('urgentRequestPanelV6')||document.getElementById('urgentRequestPanelV5');const service=serviceBySelect();if(panel)panel.classList.toggle('active',isUrgent(service))}
const serviceSelect=document.getElementById('bookingService');if(serviceSelect&&serviceSelect.dataset.v6!=='yes'){serviceSelect.dataset.v6='yes';serviceSelect.addEventListener('change',()=>{toggleUrgentPanel();window.updateTimes();window.renderBookingDateStrip()})}
const urgentBtn=document.getElementById('urgentNoTimeBtn');if(urgentBtn&&urgentBtn.dataset.v6!=='yes'){urgentBtn.dataset.v6='yes';urgentBtn.addEventListener('click',()=>{const service=serviceBySelect();if(!isUrgent(service)){alert('Спочатку оберіть термінову консультацію.');return}const name=document.getElementById('clientFullName')?.value||'',email=(document.getElementById('clientEmail')?.value||'').trim().toLowerCase(),phone=document.getElementById('clientPhone')?.value||'';if(!name||!email||!phone){alert('Заповніть ПІБ, пошту та телефон.');return}const b={id:typeof uid==='function'?uid():String(Date.now()),clientFullName:name,clientEmail:email,clientPhone:phone,clientSocial:document.getElementById('clientSocial')?.value||'',service:service.title,price:Number(service.price||0),date:todayLocal(),time:'',noTime:true,comment:document.getElementById('clientComment')?.value||'Клієнт хоче узгодити час у Telegram',status:'urgent_requested',urgent:true,zoom:typeof site==='function'?site().zoomLink:'',createdAt:new Date().toISOString()};const arr=typeof bookings==='function'?bookings():[];arr.push(b);localStorage.setItem('psy_bookings',JSON.stringify(arr));const tg=typeof site==='function'?(site().telegramUrl||'#'):'#';const box=document.getElementById('bookingResult');if(box){box.style.display='block';box.innerHTML=`<strong>Запит без часу створено.</strong><br>Напишіть психологу в Telegram, щоб узгодити годину. Після підтвердження у кабінеті зʼявиться оплата.<br><a class="btn primary" href="${tg}" target="_blank">Написати в Telegram</a>`}if(typeof renderAll==='function')renderAll()})}
async function fileData(input){const file=input.files&&input.files[0];if(!file)return'';return await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
function getSite(){try{return JSON.parse(localStorage.getItem('psy_site'))||{}}catch(e){return{}}}
function saveSite(s){localStorage.setItem('psy_site',JSON.stringify(s))}
function savedHint(input,msg='Фото збережено'){let el=document.getElementById(input.id+'Status');if(!el){el=document.createElement('small');el.className='photo-save-status';el.id=input.id+'Status';input.insertAdjacentElement('afterend',el)}el.textContent=msg}
function markPhoto(el){if(!el)return;if(el.querySelector('img'))el.classList.add('has-photo');else el.classList.remove('has-photo')}
function renderPhotos(){const s=getSite();const home=document.getElementById('homePsychologistPhoto');if(home){const url=s.homePhotoUrl||s.photoUrl||'';if(url)home.innerHTML=`<img src="${url}" alt="Фото психолога">`;markPhoto(home)}const about=document.getElementById('psychologistPhoto');if(about){const url=s.photoUrl||s.homePhotoUrl||'';if(url)about.innerHTML=`<img src="${url}" alt="Фото психолога">`;markPhoto(about)}}
function bindAdminPhoto(id,key,alsoKey){const input=document.getElementById(id);if(!input||input.dataset.v6photo==='yes')return;input.dataset.v6photo='yes';input.addEventListener('change',async()=>{const data=await fileData(input);if(!data)return;const s=getSite();s[key]=data;if(alsoKey)s[alsoKey]=data;saveSite(s);savedHint(input);renderPhotos();if(typeof renderAll==='function')renderAll()})}
function beautifyDates(){document.querySelectorAll('.booking-item,.slot-item,.home-slot-item,#selectedDayTitle').forEach(el=>{el.innerHTML=el.innerHTML.replace(/(\d{4})-(\d{2})-(\d{2})/g,'$3-$2-$1')})}
const oldRenderAll=window.renderAll||(typeof renderAll==='function'?renderAll:null);if(typeof oldRenderAll==='function'&&!window.__v6FinalPatch){window.__v6FinalPatch=true;window.renderAll=function(){oldRenderAll();bindAdminPhoto('homePhotoFile','homePhotoUrl');bindAdminPhoto('psychologistPhotoFile','photoUrl');renderPhotos();toggleUrgentPanel();window.renderBookingDateStrip();beautifyDates()}}
document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{bindAdminPhoto('homePhotoFile','homePhotoUrl');bindAdminPhoto('psychologistPhotoFile','photoUrl');renderPhotos();toggleUrgentPanel();window.renderBookingDateStrip();beautifyDates()},250))
})();
